"use client";

import React from "react";
import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-100 flex justify-center px-6 py-12">
      <div className="max-w-3xl bg-white rounded-2xl shadow-lg p-8 prose prose-gray">
        <h1 className="text-3xl font-bold text-gray-800 mb-6">
          Terms and Conditions
        </h1>
        <p className="text-sm text-black-500 mb-8">
          Last Updated: September 29, 2025
        </p>

        <h2>1. Marketplace Platform Only</h2>
        <p>
          We provide an online platform that enables users to list, buy, and sell
          goods. We are not the buyer, seller, or party to any transaction between
          users. We do not own, inspect, or guarantee any items listed on the
          Platform.
        </p>

        <h2>2. User Responsibilities</h2>
        <p>
          You are solely responsible for your use of the Platform, including
          verifying listings, item quality, and trustworthiness of other users.
          You must comply with all applicable laws and regulations.
        </p>

        <h2>3. No Guarantees or Endorsements</h2>
        <p>
          We do not guarantee the accuracy, safety, or legality of user content or
          items sold. All transactions are made at your own risk.
        </p>

        <h2>4. Payments and Transactions</h2>
        <p>
          Payments are processed through third-party providers. We are not
          responsible for disputes, fraud, failed payments, or refunds. Users must
          resolve disputes directly with each other.
        </p>

        <h2>5. Limitation of Liability</h2>
        <p>
          To the fullest extent permitted by law, we shall not be liable for any
          damages arising from your use of the Platform, including but not limited
          to loss of profits, fraudulent transactions, delivery issues, or disputes
          between users.
        </p>

        <h2>6. No Responsibility for Content</h2>
        <p>
          All content is generated by users. We are not responsible for offensive,
          misleading, illegal, or harmful content posted by others.
        </p>

        <h2>7. Prohibited Activities</h2>
        <p>
          You may not use the Platform to sell illegal or counterfeit goods,
          harass others, violate laws, or infringe intellectual property. We may
          remove content or suspend accounts at our discretion.
        </p>

        <h2>8. Indemnification</h2>
        <p>
          You agree to indemnify and hold us harmless from any claims, damages, or
          expenses arising from your use of the Platform, your transactions, or
          your violation of these Terms.
        </p>

        <h2>9. No Warranty</h2>
        <p>
          The Platform is provided “as is” without warranties of any kind. We do
          not guarantee uninterrupted service, security, or error-free operation.
        </p>

        <h2>10. Account Responsibility</h2>
        <p>
          You are responsible for securing your account and all activity under it.
          We may suspend accounts that misuse the Platform.
        </p>

        <h2>11. Governing Law</h2>
        <p>
          These Terms shall be governed by the laws of [Your State/Country],
          without regard to conflicts of law.
        </p>

        <h2>12. Changes to Terms</h2>
        <p>
          We may update these Terms at any time. Continued use of the Platform
          after changes are posted constitutes acceptance of the new Terms.
        </p>

        <h2>13. Contact Us</h2>
        <p>
          For questions about these Terms, contact us at:
          <span className="font-medium">[Your Business Email]</span>.
        </p>

        {/* Back to Login button */}
        <div className="mt-8 flex justify-center">
          <Link
            href="/Login"
            className="rounded-lg bg-blue-600 px-6 py-2 text-white font-semibold hover:bg-blue-700 transition-colors"
          >
            Back to Login
          </Link>
        </div>
      </div>
    </div>
  );
}
